### ISSUE TITLE
Can't Start game after enabling Shields (mod)

### ISSUE THREAD

**Issue by aia21** [jaxxa/RimWorld-Enhanced-Defence#10]
When i start mod (shields cuz core works properly i think )  shield can't be build (no textures when placing and then i can't do anything else (game freezes) when shields mod enabled i can't start game(black screen)

output_log:
https://www.dropbox.com/s/i8pvn0g03ntp4g5/output_log.txt?dl=0
ModsConfig:
https://www.dropbox.com/s/6li79yus3thk4ll/ModsConfig.xml?dl=0

**Comment by jaxxa** [comment]
Mod config looks good.

Can you just check that you have the .dll file in "\Mods\ED-Core\Assemblies". 

If you don't have it can you grab one of the binary releases from the Forum, GitHub is only the source.

**Comment by aia21** [comment]
thats how it look in game (when i chose some shield game freezes)
![in game](https://cloud.githubusercontent.com/assets/4209110/5903438/f8d2a914-a581-11e4-87e4-09fa57bb0fb4.jpg)
I have one .dll file (and my mods list)
![mods and assemblies](https://cloud.githubusercontent.com/assets/4209110/5903439/fdfde78c-a581-11e4-89b3-c980ccb93cd7.png)

**Comment by jaxxa** [comment]
What happens if you try it with starting a new game without the Turret Collection installed?

You can use demode to build them instantly for testing so you don't have to play right through.

**Comment by aia21** [comment]
I've just downloaded some modpack and I took from there yours mods and it worked (It contains Turret Collection)

**Comment by jaxxa** [comment]
Ok, looks like it was corrupted when you downloaded the file then.
