### ISSUE TITLE
Colonists won't plant...

### ISSUE THREAD

**Issue by hopeseekr** [jaxxa/RimWorld-Enhanced-Defence#12]
OK, I tried the 24 hour plant mod...

Colonists just stand over grow zones and chat with each other. They'll harvest, but they definitely won't plant. 

This is with a saved game created with stock Rimworld with the mod loaded after.

**Comment by jaxxa** [comment]
Hi

Can you please:
1. Confirm that you have enabled the "ED-Core" module 
2. Confirm that the "ED-Core" module is loaded before the plants 24H module
3. Check that there is a .dll in the "Assemblies" folder of ED-Core
4.What version of the game and mod are you running?
5. are there any errors in the log?

**Comment by hopeseekr** [comment]
Hi Jaxxa, I really like your avatar ;-) I was Dr. Jackson for a few years myself.

When I went to the assemblies folder, I found a readme... lol 

I guess it's *amazing* so much of what I tried worked! I'm totally from the Linux side of things. I don't even know what an sln file is ;-)

**Comment by jaxxa** [comment]
Cool, So you got it working now?

FYI the .sln file is a solution file for visual studio.

**Comment by jaxxa** [comment]
I am assuming this is working now. If not feel free to reopen the issue.
